default:
  interruptible: false
stages:
  - metadata

# metadata
metadata:
  image: harbor.containers.wurnet.nl/isric/pygeodatacrawler:1.0.4
  stage: metadata
  script:
    # init database if it does not exist
    - pip install sqlalchemy
    #- pycsw-admin.py -c setup_db -f ./pycsw.cfg
    # covert yml to iso (only changed?)
    - export pgdc_schema_path=/pyGeoDataCrawler/geodatacrawler/schemas
    - cd /pyGeoDataCrawler
    - poetry run crawl-metadata --dir=$CI_PROJECT_DIR/portals --mode=export --dir-out=/tmp
    # upload iso to pycsw (remove first, only changed?)
    - pycsw-admin.py -c load-records -f $CI_PROJECT_DIR/pycsw.cfg -p /tmp -r
  when: on_success
  only:
    - main
