default:
  interruptible: false
stages:
  - metadata

# metadata
metadata:
  image: harbor.containers.wurnet.nl/isric/pygeodatacrawler:1.0.15
  stage: metadata
  script:
    # init database if it does not exist
    # - pip install sqlalchemy
    # - pycsw-admin.py setup-db -c ./pycsw.cfg
    # covert yml to iso (only changed?)
    - export pgdc_schema_path=/pyGeoDataCrawler/geodatacrawler/schemas
    - cd /pyGeoDataCrawler
    - poetry run crawl-metadata --dir=$CI_PROJECT_DIR/portals --mode=export --dir-out=/tmp
    # upload iso to pycsw (remove first, only changed?)
    - pycsw-admin.py delete-records --config=$CI_PROJECT_DIR/pycsw.cfg -y
    - pycsw-admin.py load-records --config=$CI_PROJECT_DIR/pycsw.cfg  --path=/tmp
    # load also other xml files
    - pycsw-admin.py load-records --config=$CI_PROJECT_DIR/pycsw.cfg  --path=$CI_PROJECT_DIR/portals -r
  when: on_success
  only:
    - kenya
