default:
  interruptible: false
stages:
  - metadata

# metadata
metadata:
  image: harbor.containers.wurnet.nl/isric/pygeodatacrawler:1.0.2
  stage: metadata
  script:
    # init database if it does not exist
    - pip install sqlalchemy
    #- pycsw-admin.py -c setup_db -f ./pycsw.cfg
    # covert yml to iso (only changed?)
    - export pgdc_schema_path=/pyGeoDataCrawler/geodatacrawler/schemas
    - cd /pyGeoDataCrawler
    - pwd
    - ls /builds
    - echo "$CI_JOB_TOKEN $CI_COMMIT_TAG $CI_COMMIT_SHORT_SHA"
    - poetry run crawl-metadata --dir=/builds/$CI_JOB_TOKEN/portals --mode=export --dir-out=/tmp
   
    # upload iso to pycsw (remove first, only changed?)
    - pycsw-admin.py -c load-records -f /builds/$CI_JOB_TOKEN/pycsw.cfg -p /tmp -r
  when: on_success
  only:
    - main
